### ISSUE TITLE
async.forever error in 2.3.0

### ISSUE THREAD

**Issue by hnfmr** [caolan/async#1396]
**What version of async are you using?**
2.3.0
**Which environment did the issue occur in (Node version/browser version)**
NodeJs >= 7.6
**What did you do? Please include a minimal reproducable case illustrating issue.**
I have a function that works for async 2.1.5
```javascript
_async.forever(async function(next) {
  try {
    // do something
    next();
  } catch (err) {
    next(err);
  }
}
```
**What did you expect to happen?**
This function should run the async callback function forever...I am using NodeJs >= 7.6 so `async` is supported natively...
**What was the actual result?**
After upgrading to 2.3.0, now I get this error
`TypeError: next is not a function`

**Comment by aearly** [comment]
The `next` callback is now unnecessary, as is the error handling.  All you really need now is:

```js
_async.forever(async function() {
    // do something
}
```

**Comment by aearly** [comment]
Perhaps we should make it more clear in the docs that a final callback isn't passed to an `async` function.

**Comment by hnfmr** [comment]
Ah ok, this is good to know.. cheers

**Comment by sst2010** [comment]
> The `next` callback is now unnecessary, as is the error handling. All you really need now is:
> 
> ```js
> _async.forever(async function() {
>     // do something
> }
> ```

@aearly 

You mentioned that async function's don't have next callback with forever. Then how can one end the forever loop. For non-async functions, forever loop can be ended by calling next with an argument. How to achieve the same with async function in forever loop ??

**Comment by aearly** [comment]
I _think_  `throw false` might break out of an `async` `forever`.

However, if you have async/await, you're better off using a basic for loop.

```js
while (true) {
  // do async stuff
  await whatever();
  if(condition) break;
}
```

**Comment by sst2010** [comment]
@aearly 

Thanks for the response. I did figure out the throw way to break the forever loop. Although, I used `throw ("true")` & then checked if `error. message === "true"` in my `catch` block.

Maybe `throw ( false )` won't need `error. message` verification. Will try later.

Also, regarding your `break` solution, that is what I tried first, but node have error: `Invalid break statement` & so I used forever in the first place.

Anyways, thanks again for the response. Using throw does work as a workaround to the next callback.
